version: '3'
services:
  database:
    image: 'postgres:latest'
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: hierarchy
      POSTGRES_PASSWORD: P@ssw0rd 
      POSTGRES_DB: hierarchy
    volumes:
      - ./db-data/:/var/lib/postgresql/data/